authors:
  skytteren:
    name: Stein Kåre Skytteren
    title: Tech Lead
    display_name: SK
    gravatar: 7778d18a31077ac960fa9c7b69e2d4e9
    email: stein.kare.skytteren@penger.no
    web: http://skytteren.no
    twitter: skskytteren
    github: skytteren
