markdown: kramdown

authors:
  skytteren:
    name: Stein Kåre Skytteren
    title: Tech Lead
    display_name: SK
    gravatar: 7778d18a31077ac960fa9c7b69e2d4e9
    email: stein.kare.skytteren - AT - penger.no
    web: http://skytteren.no
    twitter: skskytteren
    github: skytteren

  oyvind:
    name: Øyvind Raddum Berg
    title: Developer
    display_name: Øyvind
    gravatar: dd1742e063aca6abf5aa83a0386120aa
    email: oyvind.raddum.berg - AT - penger.no
    twitter: olvindberg
    github: elacin
